version: '3.2'

services:
  db:
    image: postgres:latest
    container_name: url_shortener
    ports:
      - '6969:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_shortener
